// Generated by CoffeeScript 1.10.0
(function() {
  var RouteMap, clickHandling, routeMap, tempId;

  tempId = 0;

  RouteMap = (function() {
    function RouteMap(coords, links) {
      this.coords = coords;
      this.links = links;
    }

    return RouteMap;

  })();

  routeMap = new RouteMap([], []);

  ymaps.ready(function() {
    var map;
    map = new ymaps.Map("map", {
      center: [57.5262, 38.3061],
      zoom: 7
    });
    clickHandling(map);
  });

  clickHandling = function(map, routeMap) {
    return map.events.add('click', function(e) {
      var pos;
      pos = e.get('coords');
      map.geoObjects.add(new ymaps.Placemark(pos));
      routeMap.coords.push(pos);
      return console.log(routeMap.coords);
    });
  };

}).call(this);

//# sourceMappingURL=cscript.js.map
